INSERT INTO Persons (LastName,FirstName,Email,Phone) VALUES ('TESTFNAME','TESTLNAME','TEST@GMAIL.COM','1234567890');

INSERT INTO Persons (LastName,FirstName,Email,Phone) VALUES ('MANO','YAMI','TEST@GMAIL.COM','1234567890');